Importação

In [4]:
import numpy as np 

Cria um array com três elementos [1,2,3]

In [2]:
np.array([1, 2, 3 ])

array([1, 2, 3])

Cria um array com 5 elementos iguais a 0

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Similiar a .zeros(n), mas ao invés de zeros, serão inseridos 1n

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Um array de cinco elementos com valores aleatorios

In [7]:
np.empty(5)

array([4.66771335e-310, 0.00000000e+000, 5.53353523e-322, 6.92108241e-310,
       2.37151510e-322])

Retorna um array com intervalo, ness caso de 3 a 7 com um intervalo de 2

In [13]:
np.arange(3, 7, 2)

array([3, 5])

Separa os elementos linearmente

In [15]:
np.linspace(0, 7, num=3)

array([0. , 3.5, 7. ])

Forçando valores, ao passar especificar o tipo do dado

In [16]:
np.zeros(3, dtype=np.int64)

array([0, 0, 0])

Array simples, não organizado

In [17]:
arr = np.array([15, 1, 7, 11, 5, 3, 7])

Ordenando os elementos do array, por padrão em ordem crescente

In [18]:
np.sort(arr)

array([ 1,  3,  5,  7,  7, 11, 15])

Concatenando arrays

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

.array também pode lidar com outras dimensões, como matrizes

In [21]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    ])

Aqui ele irá retornar os valores guardados dentro da váriavel matriz

In [22]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Retorna quantas dimensões uma matriz possui

In [23]:
matriz.ndim

2

Retorna o tamanho da matriz

In [19]:
matriz.size

9

Retorna o formato da matriz

In [20]:
matriz.shape

(3, 3)

Mudando o formato de uma matriz

In [24]:
matriz.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Pega a estrutura e adiciona uma nova dimenção no objeto

In [27]:
array = np.array([1, 2, 3])
array[np.newaxis, :]

array([[1, 2, 3]])

Formato da nova estrutura

In [28]:
array[np.newaxis, :].shape

(1, 3)